kind: pipeline
name: cpanm

steps:
  - name: cpanm notest
    image: perl:5.28
    depends_on:
      - clone
    environment:
      FEEDRO_TOKEN_NOTEST_FAIL:
        from_secret: FEEDRO_TOKEN_NOTEST_FAIL
      FEEDRO_TOKEN_NOTEST_SUCCESS:
        from_secret: FEEDRO_TOKEN_NOTEST_SUCCESS
    commands:
      - bash cpanm-install-notest-recent.sh
  - name: cpanm with test
    image: perl:5.28
    depends_on:
      - clone
    environment:
      FEEDRO_TOKEN_FAIL:
        from_secret: FEEDRO_TOKEN_FAIL
      FEEDRO_TOKEN_SUCCESS:
        from_secret: FEEDRO_TOKEN_SUCCESS
    commands:
      - bash cpanm-install-recent.sh
