kind: pipeline
name: cpanm

steps:
  - name: cpanm notest
    image: perl:5.28
    depends_on:
      - clone
    environment:
      FEEDRO_TOEKN_NOTEST_FAIL:
        from_secret: FEEDRO_TOEKN_NOTEST_FAIL
      FEEDRO_TOEKN_NOTEST_SUCCESS:
        from_secret: feedro_toekn_notest_success
    commands:
      - bash cpanm-install-notest-recent.sh
  - name: cpanm with test
    image: perl:5.28
    depends_on:
      - clone
    environment:
      FEEDRO_TOEKN_FAIL:
        from_secret: FEEDRO_TOEKN_FAIL
      FEEDRO_TOEKN_SUCCESS:
        from_secret: FEEDRO_TOEKN_SUCCESS
    commands:
      - bash cpanm-install-recent.sh
