kind: pipeline
name: cpanm

steps:
  - name: cpanm notest
    image: perl:5.28
    depends_on:
      - clone
    environment:
      FEEDRO_TOKEN_CPANM_NOTEST:
        from_secret: FEEDRO_TOKEN_CPANM_NOTEST
    commands:
      - bash cpanm-install-notest-recent.sh
  - name: cpanm with test
    image: perl:5.28
    depends_on:
      - clone
    environment:
      FEEDRO_AUTHOR_NAME: DroneCI
      FEEDRO_TOKEN_CPANM:
        from_secret: FEEDRO_TOKEN_CPANM
    commands:
      - bash cpanm-install-recent.sh
