kind: pipeline
name: cpanm

steps:
  - name: cpanm notest
    image: perl:5.28.0
    depends_on:
      - clone
    commands:
      - bash cpanm-install-notest-recent.sh
    environment:
      FEEDRO_TOEKN_NOTEST_FAIL: $$FEEDRO_TOEKN_NOTEST_FAIL
      FEEDRO_TOEKN_NOTEST_SUCCESS: $$FEEDRO_TOEKN_NOTEST_SUCCESS
  - name: cpanm with test
    image: perl:5.28.0
    depends_on:
      - clone
    commands:
      - bash cpanm-install-recent.sh
    environment:
      FEEDRO_TOEKN_FAIL: $$FEEDRO_TOEKN_FAIL
      FEEDRO_TOEKN_SUCCESS: $$FEEDRO_TOEKN_SUCCESS
