kind: pipeline
name: cpanm
steps:
  - name: cpanm with test
    image: perl:5.28.0
    commands:
      - bash cpanm-install-recent.sh
  - name: cpanm notest
    image: perl:5.28.0
    commands:
      - bash cpanm-install-notest-recent.sh
