kind: pipeline
name: cpanm

steps:
  - name: cpanm notest
    image: perl:5.28.0
    depends_on: clone
    commands:
      - bash cpanm-install-notest-recent.sh
  - name: cpanm with test
    image: perl:5.28.0
    depends_on: clone
    commands:
      - bash cpanm-install-recent.sh

---
kind: pipeline
name: cpanm arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: cpanm notest
    image: perl:5.28.0
    depends_on: clone
    commands:
      - bash cpanm-install-notest-recent.sh
  - name: cpanm with test
    image: perl:5.28.0
    depends_on: clone
    commands:
      - bash cpanm-install-recent.sh
