# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install cpanminus
  displayName: install cpanm

- bash: |
    export FEEDRO_TOKEN_CPANM_NOTEST
    bash ./cpanm-install-notest-recent.sh
  env:
    FEEDRO_TOKEN_CPANM_NOTEST: $(FEEDRO_TOKEN_CPANM_NOTEST)
  displayName: 'Install recent modules with cpanm (notest)'
