name: 'Recent (Notest)'

on:
  push:
  schedule:
    - cron: '15 30 * * *'

jobs:
  run:
    container:
      image: perl:5.32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash cpanm-install-notest-recent.sh
        env:
          FEEDRO_AUTHOR_NAME: GithubAction
          FEEDRO_TOKEN_CPANM: ${{ secrets.FEEDRO_TOKEN_CPANM }}
